//GPA Of Each Student

SELECT 
    S.STUDENT_ID,
    S.NAME,
    ROUND(SUM(
        CASE
            WHEN M.MARKS >= 90 THEN 10
            WHEN M.MARKS >= 80 THEN 9
            WHEN M.MARKS >= 70 THEN 8
            WHEN M.MARKS >= 60 THEN 7
            WHEN M.MARKS >= 50 THEN 6
            ELSE 0
        END * SUB.CREDITS
    ) / SUM(SUB.CREDITS), 2) AS GPA
FROM STUDENTS S
JOIN MARKS M ON S.STUDENT_ID = M.STUDENT_ID
JOIN SUBJECTS SUB ON M.SUBJECT_ID = SUB.SUBJECT_ID
GROUP BY S.STUDENT_ID, S.NAME;



//Students Who Failed In More Than Two Subjects

SELECT 
    S.STUDENT_ID,
    S.NAME,
    COUNT(*) AS FAILED_SUBJECTS
FROM STUDENTS S
JOIN MARKS M ON S.STUDENT_ID = M.STUDENT_ID
WHERE M.MARKS < 50
GROUP BY S.STUDENT_ID, S.NAME
HAVING COUNT(*) > 2;



//Topper Of Each Semester

SELECT SEMESTER_ID, STUDENT_ID, NAME, TOTAL_MARKS
FROM (
    SELECT 
        M.SEMESTER_ID,
        S.STUDENT_ID,
        S.NAME,
        SUM(M.MARKS) AS TOTAL_MARKS,
        RANK() OVER (PARTITION BY M.SEMESTER_ID ORDER BY SUM(M.MARKS) DESC) AS RANK_POS
    FROM MARKS M
    JOIN STUDENTS S ON M.STUDENT_ID = S.STUDENT_ID
    GROUP BY M.SEMESTER_ID, S.STUDENT_ID, S.NAME
) RANKED
WHERE RANK_POS = 1;



//Pass Percentage By Subject

SUB.SUBJECT_ID,
    SUB.SUBJECT_NAME,
    ROUND(100.0 * SUM(CASE WHEN M.MARKS >= 50 THEN 1 ELSE 0 END) / COUNT(*), 2) AS PASS_PERCENTAGE
FROM MARKS M
JOIN SUBJECTS SUB ON M.SUBJECT_ID = SUB.SUBJECT_ID
GROUP BY SUB.SUBJECT_ID, SUB.SUBJECT_NAME;


