CREATE TABLE Students (
    STUDENT_ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50)
);



CREATE TABLE SUBJECTS (
    SUBJECT_ID INT PRIMARY KEY,
    SUBJECT_NAME VARCHAR(50),
    SEMESTER INT,
    CREDITS INT
);


CREATE TABLE MARKS (
    STUDENT_ID INT,
    SUBJECT_ID INT,
    SEMESTER_ID INT,
    MARKS INT,
    PRIMARY KEY(STUDENT_ID, SUBJECT_ID),
    FOREIGN KEY(STUDENT_ID) REFERENCES Students(STUDENT_ID),
    FOREIGN KEY(SUBJECT_ID) REFERENCES Subjects(SUBJECT_ID),
    FOREIGN KEY(SEMESTER_ID) REFERENCES Semesters(SEMESTER_ID)
);


CREATE TABLE SEMESTERS (
    SEMESTER_ID INT PRIMARY KEY,
    SEMESTER_NAME VARCHAR(20)
);


CREATE TABLE INSTRUCTORS (
    INSTRUCTOR_ID INT PRIMARY KEY,
    NAME VARCHAR(50)
);